version: '2.0'
description: Aspatial test affordances - 4 affordances, no positions
status: TEST
affordances:
- id: '0'
  name: Bed
  category: energy
  interaction_type: instant
  costs:
  - meter: money
    amount: 0.05
  operating_hours:
  - 0
  - 24
- id: '1'
  name: Hospital
  category: health
  interaction_type: instant
  costs:
  - meter: money
    amount: 0.15
  operating_hours:
  - 0
  - 24
- id: '2'
  name: HomeMeal
  category: food
  interaction_type: instant
  costs:
  - meter: money
    amount: 0.04
  operating_hours:
  - 0
  - 24
- id: '3'
  name: Job
  category: income
  interaction_type: instant
  costs:
  - meter: energy
    amount: 0.15
  operating_hours:
  - 8
  - 18
